[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "agentsociety-community"
version = "0.3.2"
description = "A community library for customizing agent/block for AgentSociety"
authors = [
    { name = "Jun Zhang", email = "zhangjun990222@gmail.com" },
]
license = { file = "LICENSE" }
readme = "README.md"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: POSIX :: Linux",
    "Operating System :: MacOS :: MacOS X",
]
requires-python = ">=3.11"
dependencies = [
    "agentsociety>=1.5.0a9",
]

[project.urls]
Homepage = "https://github.com/tsinghua-fib-lab/agentsociety-community"
Repository = "https://github.com/tsinghua-fib-lab/agentsociety-community.git"
Issues = "https://github.com/tsinghua-fib-lab/agentsociety-community/issues"
